import { useState } from 'react';
import { EntityBrowser } from './components/EntityBrowser';
import { AssetEditor } from './components/AssetEditor';
import { VideoAsciiTool } from './components/VideoAsciiTool';
import { ImageAsciiTool } from './components/ImageAsciiTool';
import { ModelBrowser } from './components/ModelBrowser';
import type { WikiEntity, WikiCategory } from './types';

// Import wiki data (generated by export script)
import wikiData from './data/wiki-export.json';

const CATEGORIES: WikiCategory[] = [
  'items',
  'enemies',
  'travelers',
  'pantheon',
  'wanderers',
  'shops',
  'domains',
  'trophies',
  'factions',
];

type ViewMode = 'entities' | 'video' | 'image' | 'models';

export default function App() {
  const [viewMode, setViewMode] = useState<ViewMode>('entities');
  const [selectedCategory, setSelectedCategory] = useState<WikiCategory>('items');
  const [selectedEntity, setSelectedEntity] = useState<WikiEntity | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [assetsDir, setAssetsDir] = useState<FileSystemDirectoryHandle | null>(null);

  // Get entities for current category
  const entities = (wikiData as Record<WikiCategory, WikiEntity[]>)[selectedCategory] || [];

  // Filter by search
  const filteredEntities = searchQuery
    ? entities.filter(e =>
        e.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        e.slug.toLowerCase().includes(searchQuery.toLowerCase())
      )
    : entities;

  // Request directory access for saving files
  const requestDirectoryAccess = async () => {
    try {
      const handle = await (window as any).showDirectoryPicker({
        mode: 'readwrite',
        startIn: 'documents',
      });
      setAssetsDir(handle);
      console.log('Directory access granted:', handle.name);
    } catch (err) {
      console.error('Directory access denied:', err);
    }
  };

  return (
    <div style={styles.container}>
      {/* Header */}
      <header style={styles.header}>
        <h1 style={styles.title}>NDG Asset CMS</h1>
        <div style={styles.headerActions}>
          <span style={styles.entityCount}>
            {filteredEntities.length} entities
          </span>
          {assetsDir ? (
            <span style={styles.dirBadge}>
              Folder: {assetsDir.name}
            </span>
          ) : (
            <button onClick={requestDirectoryAccess} style={styles.dirButton}>
              Set Assets Folder
            </button>
          )}
        </div>
      </header>

      <div style={styles.main}>
        {/* Sidebar - Categories */}
        <aside style={styles.sidebar}>
          <div style={styles.searchBox}>
            <input
              type="text"
              placeholder="Search entities..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={styles.searchInput}
              disabled={viewMode === 'video'}
            />
          </div>
          <nav style={styles.categoryNav}>
            {/* Entity categories */}
            <div style={styles.sectionLabel}>Entities</div>
            {CATEGORIES.map((cat) => (
              <button
                key={cat}
                onClick={() => {
                  setViewMode('entities');
                  setSelectedCategory(cat);
                  setSelectedEntity(null);
                }}
                style={{
                  ...styles.categoryButton,
                  ...(viewMode === 'entities' && selectedCategory === cat ? styles.categoryButtonActive : {}),
                }}
              >
                {cat}
                <span style={styles.categoryCount}>
                  {((wikiData as Record<WikiCategory, WikiEntity[]>)[cat] || []).length}
                </span>
              </button>
            ))}

            {/* Tools */}
            <div style={{ ...styles.sectionLabel, marginTop: '16px' }}>Tools</div>
            <button
              onClick={() => {
                setViewMode('image');
                setSelectedEntity(null);
              }}
              style={{
                ...styles.categoryButton,
                ...(viewMode === 'image' ? styles.categoryButtonActive : {}),
              }}
            >
              Image ASCII
            </button>
            <button
              onClick={() => {
                setViewMode('video');
                setSelectedEntity(null);
              }}
              style={{
                ...styles.categoryButton,
                ...(viewMode === 'video' ? styles.categoryButtonActive : {}),
              }}
            >
              Video ASCII
            </button>
            <button
              onClick={() => {
                setViewMode('models');
                setSelectedEntity(null);
              }}
              style={{
                ...styles.categoryButton,
                ...(viewMode === 'models' ? styles.categoryButtonActive : {}),
              }}
            >
              3D Models
            </button>
          </nav>
        </aside>

        {/* Main Content */}
        <main style={styles.content}>
          {viewMode === 'models' ? (
            <ModelBrowser />
          ) : viewMode === 'image' ? (
            <ImageAsciiTool />
          ) : viewMode === 'video' ? (
            <VideoAsciiTool />
          ) : selectedEntity ? (
            <AssetEditor
              entity={selectedEntity}
              assetsDir={assetsDir}
              onClose={() => setSelectedEntity(null)}
            />
          ) : (
            <EntityBrowser
              entities={filteredEntities}
              category={selectedCategory}
              onSelectEntity={setSelectedEntity}
            />
          )}
        </main>
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    background: '#0a0a0a',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 24px',
    background: '#141414',
    borderBottom: '1px solid #2a2a2a',
  },
  title: {
    fontSize: '1.25rem',
    fontWeight: 600,
    color: '#E90441',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  entityCount: {
    color: '#888',
    fontSize: '0.875rem',
  },
  dirBadge: {
    padding: '4px 12px',
    background: '#1a3d1a',
    borderRadius: '4px',
    fontSize: '0.75rem',
    color: '#6ddf6d',
  },
  dirButton: {
    padding: '6px 12px',
    background: '#E90441',
    border: 'none',
    borderRadius: '4px',
    color: 'white',
    fontSize: '0.75rem',
    cursor: 'pointer',
  },
  main: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  sidebar: {
    width: '200px',
    background: '#111',
    borderRight: '1px solid #2a2a2a',
    display: 'flex',
    flexDirection: 'column',
  },
  searchBox: {
    padding: '12px',
    borderBottom: '1px solid #2a2a2a',
  },
  searchInput: {
    width: '100%',
    padding: '8px 12px',
    background: '#1a1a1a',
    border: '1px solid #333',
    borderRadius: '4px',
    color: '#e0e0e0',
    fontSize: '0.875rem',
  },
  categoryNav: {
    display: 'flex',
    flexDirection: 'column',
    padding: '8px',
    gap: '4px',
    overflowY: 'auto',
  },
  categoryButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    background: 'transparent',
    border: 'none',
    borderRadius: '4px',
    color: '#888',
    fontSize: '0.875rem',
    cursor: 'pointer',
    textAlign: 'left',
    textTransform: 'capitalize',
  },
  categoryButtonActive: {
    background: '#1a1a1a',
    color: '#E90441',
  },
  categoryCount: {
    fontSize: '0.75rem',
    color: '#555',
  },
  sectionLabel: {
    fontSize: '0.65rem',
    fontWeight: 600,
    color: '#555',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    padding: '8px 12px 4px',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: '24px',
  },
};
